version: '3'
services:
  ruby_server:
    build:
      context: ./
    ports:
     - "4567:8080"
  nginx_server:
    image: nginx
    volumes:
      - ./deployment-files/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    command: [nginx, '-g', 'daemon off;']
    links:
      - ruby_server:ruby_server
    depends_on:
      - ruby_server
